import { createStyles } from "@mantine/core";
import { GLOBAL_STYLES } from "../../../Config";

const useStyles = createStyles((theme, params) => ({
  dialogOuterWrapper: {
    position: "fixed",
    width: "100%",
    height: "100vh",
    maxHeight: "100vh",
    top: 0,
    left: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 21213123,
  },
  dialogInnerWrapper: {
    position: "fixed",
    width: "100%",
    height: "100vh",
    maxHeight: "100vh",
    backgroundColor: "#34317D",
    opacity: "0.9",
    top: 0,
    left: 0,
    zIndex: 21213123,
  },
  container: {
    display: "flex",
    padding: "40px",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: "16px",
    background: "#FFF",
    width: "600px",
    position: "relative",
    zIndex: 21213127,
  },
  img: {
    position: "absolute",
    right: "28px",
    top: "28px",
    width: "12px",
    height: "12px",
    color: "#34317D",
    zIndex: 9999999999,
    cursor: "pointer",
  },
  iframeWrapper: {
    width: "100%",
    marginTop: "24px",
  },
  warningImg: {
    width: "53.398px",
    height: "60px",
  },
  mainTitle: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "32px",
    fontWeight: 800,
    textTransform: "capitalize",
    margin: 0,
    marginTop: "24px",
  },
  para: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 400,
    margin: 0,
    marginTop: "8px",
  },
  btnWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    columnGap: "10px",
    marginTop: "32px",
  },
  cancelBtn: {
    display: "flex",
    border: `1px solid ${GLOBAL_STYLES.BUTTON_BLUE_BACKGROUND}`,
    color: GLOBAL_STYLES.BUTTON_BLUE_BACKGROUND,
    background: "transparent",
    padding: "10px 24px",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 700,
  },
  upgradeBtn: {
    backgroundColor: GLOBAL_STYLES.BUTTON_BLUE_BACKGROUND,
    display: "flex",
    padding: "10px 24px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    color: "#FFF",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 700,
  },
}));

export default useStyles;
