import { createStyles, keyframes } from "@mantine/core";

const spin = keyframes`
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
`;

import { GLOBAL_STYLES } from "../../../Config";
const useStyles = createStyles((theme, params) => ({
  customImg: {
    objectFit: "fill",
    marginLeft: "9px",
    zIndex: 100000,
  },
  customImgBtnb: {
    objectFit: "fill",
    marginLeft: "2px",
    marginRight: "5px",
    zIndex: 100000,
  },
  saveProfileSpan: {
    backgroundColor: "#6E40C5",
    //   padding: "3px",
    borderRadius: "32px",
    //   width: "205px",
    //height: "37px",
    display: "inline-flex",
    alignItems: "center",
    whiteSpace: "nowrap",
    overflow: "visible",
    position: "relative",
    zIndex: 100000,
  },
  saveProfileBtn: {
    color: "#FFF",
    fontFamily: "Poppins",
    fontSize: "14px",
    fontWeight: 600,
    backgroundColor: "transparent",
    display: "inline-flex",
    padding: "3px 0px",
    flexDirection: "row-reverse",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "32px",
    marginRight: "2px",
    // marginLeft: '0px',
    paddingLeft: "4px",
    zIndex: 100000,
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  dropdown: {
    position: "absolute",
    top: "55%",
    width: "100%",
    left: 0,
    zIndex: 10,
    flexDirection: "column",
    gap: "1px",
    display: "flex",
    paddingBottom: "10px",
    backgroundColor: "#6E40C5",
    borderRadius: "0 0 17px 17px",
    padding: "10px",
  },
  dropdownBtn: {
    color: "#FFF",
    marginTop: "8px",
    fontFamily: "Poppins",
    fontSize: "14px",
    height: "29px",
    fontWeight: 600,
    border: "1px solid #FFFFFF",
    backgroundColor: "#F5F1FB1A",
    display: "inline-flex",
    padding: "3px 10px",
    width: "100%",
    borderRadius: "32px",
    alignItems: "center",
    "&:hover": {
      backgroundColor: "#F5F1FB",
      color: "#2F3178",
    },
  },
  emptyListSpan: {
    height: "220px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
    background: "#FFFFFF",
    marginTop: "10px",
    borderRadius: "17px",
  },
  filledListSpan: {
    minHeight: "100px",
    maxHeight: "245px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    background: "#FFFFFF",
    marginTop: "8px",
    borderRadius: "17px",
    padding: "10px",
  },
  searchInput: {
    borderRadius: "8px !important",
    height: "27px !important",
    border: "0.5px solid #DFDFDF !important",
    paddingTop: "5px !important",
    paddingBottom: "5px !important",
    paddingLeft: "30px !important",
    color: "#696A6F !important",
    "&:hover": {
      borderColor: "#DFDFDF !important",
    },
    "&:focus": {
      outline: "none !important",
    },
  },
  showList: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "start",
    marginTop: "7px",
    Height: "80px",
    maxHeight: "165px",
    borderBottom: "0.5px solid #DFDFDF",
    overflowY: "auto",
    paddingBottom: "5px",
  },
  singleList: {
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    marginTop: "5px",
  },
  searchContainer: {
    position: "relative",
    width: "100%",
  },
  searchIcon: {
    position: "absolute",
    left: "10px",
    top: "50%",
    transform: "translateY(-50%)",
  },
  listFooter: {
    marginTop: "10px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: "5px",
  },
  loader: {
    border: "2px solid #f3f3f3",
    borderTop: "2px solid #3498db",
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    animation: `${spin} 2s linear infinite`,
    margin: "0 auto",
  },
}));

export default useStyles;
