import { Global } from "@emotion/react";

export const CLASS_NAMES = {
  COMMENTS_COMMENT_ENTITY: ".comments-comment-entity",
  COMMENTS_THREAD_ENTITY: ".comments-thread-entity",
  T_14: "t-14",
  P_lowEmphasis: "p[class*='_lowEmphasis']",
  LI_EXPERIENCE_ENTITY: "li._experience-entry_1irc72",
  LI_EDUCATION_ENTITY: "li._education-entry_aos46q",
  LI_LIST_ITEM: "li.artdeco-list__item",
  ENTITY_LIST_FORM: "div[data-test-text-entity-list-form-component]",
  UL_LIST_STYLE_NONE: "ul.list-style-none article",
  FEED_SHARED_UPDATE_V2: ".feed-shared-update-v2__commentary, .update-components-update-v2__commentary, .feed-shared-update-v2",
  COMMENTS_POST_META_H3_SPAN_COMMENTS__TEXT: ".comments-post-meta h3 span.comments-post-meta__name-text",
  DIV_COMMENTS_COMMENT_ITEM_SHOW_MORE_TEXT: "div.comments-comment-item__inline-show-more-text",
  COMMENTS_SOCIAL_ACTIVITY_COMMENTS_REPLIES_LIST: ".comment-social-activity .comments-replies-list",
  t14_UPDATE_COMPONENTS_title: ".t-14.update-components-article__title",
  COMPOSE_FORM__MESSAGE_FIELD: ".compose-form__message-field,textarea[name='message']",
  CONTRIBUTION_TEXT_AREA: ".contribution-text-area",
  COMMENTS_COMMENT_EDIT__SUBACTION_BAR: ".comments-comment-edit__subaction-bar",
  PULSE_TITLE: ".pulse-title",
  POWERED_BY_AI: ".powered-by-ai",
  MAIN__CONTENT_P_SPAN: ".article-main__content p span",
  CONTRIBUTION_HELPER_TEXT: ".contribution-helper-text",
  SHARE_CREATION_STATE__CONTENT: ".share-creation-state__content-scrollable",
  DATA_TEST_PUBLISHING_AUTHOR_NAME: '[data-test-publishing-author-name="true"] b',
  UPDATE_COMPONENTS_ACTOR__NAME_SPAN: ".update-components-actor__name span[aria-hidden='true']",
  SECTIONS_ARTDECO_CARD: "section.artdeco-card",
  DIV_MT2_RELATIVE: "div.mt2.relative",
  SPAN_ARTDECO_HOVERABLE_TRIGGER_ARTDECO_HOVERABLE_TRIGGER_EMBER_VIEW:
    "span.artdeco-hoverable-trigger.artdeco-hoverable-trigger--content-placed-bottom.artdeco-hoverable-trigger--is-hoverable.ember-view",
  SECTIONS_HEADER_SQH8TM: "section._header_sqh8tm",
  DIV_INSET_PADDING_SQH8TM: "div._inset-padding_sqh8tm",
  P_CLASS_BODYTEXT_NTH_TYPE: "p[class*='_bodyText']:nth-of-type(1)",
  P_CLASS_BODYTEXT_NTH_TYPE2: "p[class*='_bodyText']:nth-of-type(2)",
  CIRCLE_ENTITY_8_LAZY_IMAGE: "img.circle-entity-8.lazy-image.ember-view",
  CIRCLE_ENTITY_6_LAZY_IMAGE: "img.circle-entity-6.lazy-image",
  DATA_PERSON_NAME_MAIN: 'h1[data-anonymize="person-name"]',
  DATA_ACTION_MENU_OVERFLOW: '[aria-label="Open actions overflow menu"]',
  DATA_BASIC_LINKEDIN_LINK: 'li a[href*="/in/"]',
  DATA_HUE_MENU: '[id^="hue-menu-"]',
  DATA_TAG_LINE_TEXT: ".text-body-medium",
  DATA_HEAD_LINE_TEXT: 'span[data-anonymize="headline"]',
  DATA_EXP_LIST_ITEM: ".mr1.t-bold span",
  DATA_SUB_TITLES_MAIN: "t-black--light",
  DATA_EXP_JOB_TITLE: "h2[data-anonymize='job-title']",
  DATA_EXP_COMPANY_TITLE: "p[data-anonymize='company-name']",
  DATA_EXP_TIME_PERIOD: "span._position-time-period-range_1irc72",
  DATA_EXP_TIME_LOCATION: "p._position-location_1irc72",
  DATA_EXP_DESCRIPTION: "div._multi-position-description_1irc72",
  DATA_EXP_EDUCATION_LIST: "ul._education-list_aos46q",
  DATA_EXP_INSTUATATION_LIST: 'h3[data-anonymize="education-name"] a',
  DATA_EXP_DEGREE_LIST: "h4.a11y-text + span",
  DATA_EXP_STUDY_LIST: "h4.a11y-text + span + h4.a11y-text + span",
  DATA_EXP_TIMELINE_LIST: "p._lowEmphasis_1i6ulk span[datetime]",
  Global_NAV__LINK_ME_MENU_TRIGGER: ".global-nav__primary-link-me-menu-trigger",
  LINKEDIN_LINK_TOP: 'header a[href*="/in/"]',
  ARTDECO_DROPDOWN_CONTENT_INNER: ".artdeco-dropdown__content--is-open",

  MAIN_SCAFFOLD_LAYOUT__MAIN: "main",
  TOP_CARD_TEXT_DETAILS_CONTACT_INFO: "top-card-text-details-contact-info",
  ARTDECO_MODAL__DISMISS: ".artdeco-modal__dismiss",
  INJECT_CONTECT_INFO: "inject-contect-info",
  PV_PROFILE_SECTION_SECTION_INFO_SECTION_INFO: ".pv-profile-section__section-info.section-info",
  DIV_REIA__PV_CONTACT_INFO: 'div[aria-labelledby="pv-contact-info"]',
  CONTENT_MAIN_HOMEPAGE_V2_CONSISTENT: ".content-main-homepage-v2--consistent",
  POST_TEXT_BUTTON_1D1VLQ_UNSTYLED_BUTTON_4EDPGZ: "._post-text-button_1d1vlq._unstyled-button_4edpgz",
  CONTENT_WIDTH_1DTBSB: "._content-width_1dtbsb",
  ARTDECO_MODAL_CONTENT_EMBER_VIEW: ".artdeco-modal__content.ember-view",
  CONTACT_INFO_FORM_PHONE: ".contact-info-form__phone",
  CONTACT_INFO_CTA: ".contact-info-cta",
  LEAD_SIDESHEET_HEADER_BUTTON: ".lead-sidesheet header button",
  LISTS_DETAIL_VIEW_PROFILE_NAME_LINK: ".lists-detail__view-profile-name-link",
  FRAGMENTED_LINKS: ".fragmented-links",
  SN_VIEW_LEAD_PANEL: "view_lead_panel_via_search_lead_name",
  SN_VIEW_LEAD_NAME_VIA_LEADERSHIP_EXPLORER: "view_lead_via_relationship_explorer_lead_name",
  UPDATE_OUTLET: "update-outlet",
  COMMENT_BOX_FORM_CONTAINER: "comments-comment-box__form-container",
  COMMENT_BOX_FORM_CONTAINER2: "comments-comment-box__form",
  POST_POPUP_CONTAINER_CLASS: "feed-shared-update-detail-viewer__content",
  ENTITY_RESULT__CONTENT_CONTAINER: "entity-result__content-container",
  UPDATE_RESULT__CONTENT_CONTAINER: "update-components__content-container",
  PROFILE_CREATOR__CONTENT_CONTAINER: "profile-creator-shared-feed-update__container",
  INVITATION_DIALOG: "artdeco-modal__content",
  ENTITY_RESULT__CONTENT_TITLE: "entity-result__title-text",
  UPDATE_RESULT__CONTENT_TITLE: "update-components-actor__name",
  COMMENT_BOX_TEXT_EDITOR: "comments-comment-box-comment__text-editor",
  COMMENT_BOX_WITH_ID: "comments-comment-box",
  COMMENT_BOX_WITH_ID2: "comments-comment-box--cr",
  COMMENT_EDITOR: "ql-editor",
  CONTRIBUTION_TEXT_WRAPPER: "contribution-text-area-wrapper",
  MESSAGE_EDITOR: "msg-form__contenteditable",
  EXTENSION_BUTTON_OPEN_POPUP: "extension-button-open-popup",
  POST_TEXT_OUTER_CONTAINER: "feed-shared-update-v2__description-wrapper, .feed-shared-update-v2__description",
  POST_TEXT_SPAN_CONTAINER: "break-words",
  AUTHOR_NAME_CONTAINER: "update-components-actor__name, .update-components-actor__single-line-truncate",
  MESSAGE_BOX_CONTAINER: "msg-form__msg-content-container",
  MESSAGE_FORM_FOOTER: "msg-form__footer",
  MESSAGE_FORM: "msg-form",
  MESSAGE_THREAD_CONTAINER: "msg-s-message-list-content",
  MESSAGE_TEXT_LIST_ITEM: "msg-s-message-list__event",
  MESSAGE_TEXT_FROM_USER: "msg-s-message-group__name",
  MESSAGE_TEXT_CONTENT: "msg-s-event__content",
  OCCLUDABLE_UPDATE: "occludable-update",
  RELATIVE: "relative",
  ENTITY_RESULT_CONTENT_SUMMARY: "entity-result__content-summary--3-lines",
  EMBER_VIEW: "ember-view",
  ART_DECO_CARD: "artdeco-card",
  MESSAGE_OVERLAY_CONVERSATION_BUBBLE: "msg-overlay-conversation-bubble",
  MESSAGE_OVERLAY_CONVERSATION_BUBBLE_HEADER: "msg-overlay-conversation-bubble_header",
  COMMENTS_COMMENT_ITEM: ".comments-comment-item",
  COMMENTS_HIGHLIGHTED_COMMENT_ITEM: "comments-highlighted-comment-item",
  COMMENTS_COMMENT_ITEM_HIGHLIGHTED: "comments-comment-item--highlighted",
  COMMENTS_COMMENT_ITEM_CONTENT_BODY: "comments-comment-item-content-body",
  COMMENTS_HIGHLIGHTED_COMMENT_ITEM_CONTENT_BODY: "comments-highlighted-comment-item-content-body",
  COMMENTS_COMMENT_ITEM_SPAN_CONTAINER: "comments-comment-item__main-content",
  COMMENT_COMMENT_ITEM_POST_META: "comments-comment-item__post-meta",
  COMMENT_POST_META_NAME_TEXT_SPAN_CONTAINER: "comments-post-meta__name-text",
  DATA_QL_EDITOR_CONTENT_EDITABLE: "data-test-ql-editor-contenteditable",
  COMMENTS_COMMENT_MAIN_ELEMENT: "comments-comment-entity",
  COMMENTS_COMMENT_META_DESCRIPTION_TITLE: "comments-comment-meta__description-title",
  COMMENTS_COMMENT_CONTENT_ELEMENT: "comments-comment-item__inline-show-more-text",
  COMMENTS_COMMENT_META_ACTOR: "comments-comment-meta__actor",

  SHARE_BOX: "share-box",
  LINKDLIN_FEED_MAIN_LAYOUT: "scaffold-layout__main",
  SN_FEED_MAIN_LAYOUT: "hue-web__artdeco-migration-scope",
  EXTENSION_FEED_CONTAINER: "linkdin-exention-feed-container",
  SHARE_CREATION_STATE_FOOTER: "share-creation-state__footer",
  CREATE_POST_MODAL_CLOSE_BUTTON: "artdeco-modal__dismiss",
  INVITATION_NOTE_TEXT_AREA: "connect-button-send-invite__custom-message",
  PVS_LIST_OUTER_CONTAINER: "pvs-list__outer-container",
  PVS_LIST: "pvs-list",
  TEXT_INPUT_CONTAINER: "artdeco-text-input--container",
  MODAL_HEADER: "share-to-linkedin-modal__header",
  // SALES_NAVIGATOR_COMMENT:"ql-editor ql-blank",
  SALES_MESSAGE_PAGE: "artdeco-hoverable-trigger--content-placed-top",
  SALES_MESSAGE_PAGE_CONTAINER: "_compose-form__container_jrrmou",
  SALES_MESSAGE_PAGE_CONTAINER2: "_form_jrrmou",
  SALES_MESSAGE_SEND_BUTTON: "ember-view._button_ps32ck._small_ps32ck._primary_ps32ck._left_ps32ck._container_iq15dg,ember-view[id^=ember][data-sales-action]",
  SALES_CONNECT: "_textarea_1jm0zx",
  EDIT_COMMENT_CONTAINER: "comments-comment-edit",
  // PROFILE_BTN_CONTAINER: "pv-top-card-v2-ctas",
  PROFILE_BTN_CONTAINER: "pv-profile-body-wrapper",
  SN_PROFILE_BTN_CONTAINER: ".content-main-homepage-v2--consistent section#profile-card-section",
  SN_PROFILE_BTN_CONTAINER_search: "lead-sidesheet-content",
  EXTENSION_PROFILE_BUTTON: "extension-profile-button",
  EXTENSION_RECENT_ACTIVITIES_BUTTON: "extension-recent-activities-button",
  PROFILE_IMAGE: "pv-top-card-profile-picture__image--show",
  PROFILE_URL: "ember-view.block",
  PERSONAL_PROFILE_IMAGE: "profile-photo-edit__preview",
  COMMENT_AVATAR_IMAGE:"[data-test-author-photo], .feed-shared-avatar-image img",
  PROFILE_AVATAR_BUTTON:"[data-control-name='view_user_menu_from_app_header'] span"
};

export const ELEMENT_ID = {
  MESSAGE_THREAD_OTHER_USER: "thread-detail-jump-target",
  EXPERIENCE_DIV_ID: "experience",
  PROFILE_EDIT_FORM_PAGE_HEADER: "profile-edit-form-page-header",
  EDUCATION_DIV_ID: "education",
  LICENSES_AND_CERTIFICATIONS_DIV_ID: "licenses_and_certifications",
  PROFILE_URL: "ember687",
  RECOMMENDATION_TEXT_AREA:
    "multiline-text-form-component-profileEditFormElement-WRITE-RECOMMENDATION-recommendation-11-recommendationText",
};

export const PAGE_PATH = {
  POSTS: "/posts",
  FEEDUPDATE: "/feed/update",
  SALES: "/sales",
  PROFILE: "/in",
  SEARCH: "/search",
  RECENT_ACTIVITY: "recent-activity",
};

export const extensionPage = "https://evyai.com";
export const extension_update_page = "https://evyai.com/updating-evyai/";

export const APP_VERSION = "1.4.030";

export const LOCAL_STORAGE_KEYS = {
  EXISTING_LINKEDIN_URL: "LI_URL_G",
  LINKEDIN_URL: "LI_URL",
  SAVE_BUTTON_TOP_LOCATION: "l_po_y",
  SAVE_BUTTON_RIGHT_LOCATION: "l_po_r",
  LOGGED_IN:"loggedIn"
};

export const CHROME_STORAGE_KEYS = {
  accessToken:"accessToken",
  uid:"uid",
  refreshToken:"refreshToken"
}
